NUMERO_DE_PROCESOS = 4
DEFAULT_FRECUENCIA_EN_SEGUNDOS = 1200
DEFAULT_MARGEN = 2/3
DESVIACION_POS_SIGNIFICATIVA_SEGUNDOS = 300
DESVIACION_NEG_SIGNIFICATIVA_SEGUNDOS = -180
LINEA_OMNIBUS_ANALISIS = 'C.U.T.C.S.A. 109'
PANDEMIA = False
NUMERO_PARADAS_MAS_VENDIDAS = 15